# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4f6897af7251e8ec3915abef0a0ae7d15c4092a5999372faef7f3f96e56041f311be9d06b6cad4cd48d8fb75bb13777d28bca8d120c1851d610767e4ad867e1
  twitter_api_key: J3P28TZ46fwf8u7Py0GmBuPJY
  twitter_api_secret: dfdfdkelAguHnxNLWFZnN5OPhmjEMIwQ9efZeP7BS4iJc47Fa4
test:
  secret_key_base: 8abfb08882b0b1742dff56ac932268a8a3c125526c33d2a57fba622a6d97a3dff928435da381e08c302f3a2db4e796363ed3d68af801e643ea295f99477918b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
